### ISSUE TITLE
"The kernel appears to have died" at import Phecode

### ISSUE THREAD

**Issue by methionine23** [nhgritctran/PheTK#1]
Hello, my Jupyter kernel crashes when I run from PheTK.Phecode import Phecode. What compute resources do you recommend to prevent this? Or other suggestions to resolve it. Thank you!

**Comment by nhgritctran** [comment]
Hello - How did you install PheTK? Which platform and configuration are you using? What other commands were you running in the same code block that caused the issue? An import statement should not cause a kernel to crash. If possible, a screenshot would help too.

**Comment by methionine23** [comment]
Thank you for the quick reply! It happened at mapping ICD code to phecodeX step with 50G memory. I wonder if the issue is from the file or the workstation. Didn't find much from %debug, but may try another computer. Is there a general memory recommendation?

**Comment by nhgritctran** [comment]
The phecode mapping step from ICD code is a bit memory intensive. I just did a quick test on All of Us workbench with current v7 data, and a 8CPU >=30GB RAM VM (standard VM or main VM in a dataproc cluster) worked fine for phecodeX mapping for all participants in database. 

Without knowing more details, such as cloud or local platform, ICD code data size, available memory, other custom works in your workflow, background processes, OS, etc., I would say try increasing the available memory till it works.

If you often work with a biobank database, e.g., All of Us, you could do this phecode mapping step once for the entire database, and use it for future studies drawn from that database, unless something changes in the database or PheTK mapping method, e.g., updated database, updated phecode version, etc.

**Comment by methionine23** [comment]
I found an issue related to the system used, and it works now. Thank you for your help.
