### ISSUE TITLE
Remove non-converging points from graph

### ISSUE THREAD

**Issue by emikowaight** [nhgritctran/PheTK#4]
Hello,
I have been using your PheTK tool for my thesis (thank you by the way it is great). The issue I am having is that with some of my analyses there are a few values that have very intense negative log P-values, but they do not converge, thus they are likely an artifact of some kind. The problem is when the PheWAS is graphed, these values are such outliers I cannot actually see any of the other data because the whole graph gets squished so much (see screenshots attached). Is there any way to remove these artifacts from the analysis for a cleaner overall output?
Thank you,
Emiko
<img width="825" alt="Screenshot 2024-07-10 at 9 43 00 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/1e83a3c6-d93b-445e-9d2c-1688a579f3e4">
<img width="1376" alt="Screenshot 2024-07-10 at 9 44 26 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/62d2a9b2-b796-42e6-b137-b836a9975ada">

**Comment by nhgritctran** [comment]
Hello Emiko, I glad it is useful for you! We intentionally keep the non-converged phecodes so users can do further investigation if needed as they are not necessarily artifacts, e.g., perfect separation can cause convergence issue in regression. A simple way is to filter the PheWAS result csv file to keep only just converged phecodes, save as new csv file and use the new file for plotting.

**Comment by nhgritctran** [comment]
PheTK was updated to add the feature to keep or remove non-converged phecodes for plotting since version 0.1.44.
