### ISSUE TITLE
[Question] independent_variable_of_interest Values in PheTK.PheWAS

### ISSUE THREAD

**Issue by JuseTiZ** [nhgritctran/PheTK#5]
Hello,

Thank you for developing this great tool! I have some questions about using `python -m PheTK.PheWAS`:

Can the `independent_variable_of_interest` column consist of numbers other than 0 or 1? Specifically, if I enter values like 2, 3, 4, or larger numbers, will it work as expected? I want to use the number of mutations each individual carries as a feature for the PheWAS analysis. Currently, entering numbers other than 0 and 1 does not cause errors during analysis, but I'm not sure if PheTK is processing them correctly.

Looking forward to your reply!

**Comment by nhgritctran** [comment]
Thank you for the positive feedback!

In PheWAS, each regression would be phecode ~ vairable_of_interest + covariates + constant. Based on how you set it up, it should be interpreted as a ordinal variable in a standard logistic regression, e.g., one unit increase of your variable would represent certain change in beta coefficient/odds ratio.

In general, the types of your variable of interest can be of any type, e.g., binary (having a genotype/condition or not), ordinal (having a order of ranking), or continuous (such as lab measurements, etc.), and result interpretation would change accordingly.

**Comment by JuseTiZ** [comment]
That's clear, thank you!
